### PR TITLE
chore: add contribution info to readme

### PR DESCRIPTION
**Pull request by argoyle**
Something like this? @opsiorobinostlund @robinostlund @henricm

### CODE REVIEW

**Comment by argoyle** [comment]
Shamelessly stolen from HA's contribution-guide and adapted. 😆

**Comment by henricm** [comment]
Looks great!

**Comment by henricm** [comment]
Btw. I noticed Gitter is all changed. Needed to install new app on mobile. Are you notified when someone's writes on Gitter? I don't think I am any longer but not ve installed the new app as described on their site.

**Comment by robinostlund** [comment]
@argoyle yeah exactly like this 😄

**Pull request merged**
