### PR TITLE
Handle missing values

### PR DESCRIPTION
**Pull request by argoyle**
@jonasbkarlsson Could this be a valid solution to the problem in #76 ? Would it introduce any strange side-effect? I don't see that the energy values ever should go backwards, right? @danielolsson100 Any thoughts?

### CODE REVIEW

**Comment by danielolsson100** [comment]
I don't think that we need a fix for this strange issue.
I have seen that HA can mess up the statistic counters during upgrade or reboot of HA after a powerfailure. Perhaps that is the case? @argoyle

**Comment by jonasbkarlsson** [comment]
I can't find any traces of an upgrade or reboot of HA around the time of the issue. My HA is running on a Raspberry Pi, which has more than a week of `uptime`. I checked the `journalctl`, and HA related logs looked normal.

However, I also have a NodeRED running, and at the time of the issue, it logged errors from the nodes reading the MQTT messages from the EnergyHub. So I'm guessing that the EnergyHub sent some garbage messages.

**Comment by argoyle** [comment]
Sorry, could have been more clear and this should perhaps have been two different PR's. This actually solves two problems (I have separated the changes in two different commits actually).

1. My problem (on powerloss) is actually due to us using 0 as a "default" value for several of the sensors and any saved state is ignored since we were always writing a new state using the default value of no value was provided by the EnergyHub/ESM/ESO/SSO. That is fixed by the first commit.
2. @jonasbkarlsson problem might have been caused by the EnergyHub not sending correct values (or perhaps us counting all events regardless of if they had any value for the sensor in question when calculating the average, which is actually also fixed by the first commit now). Since the contract for state class total increasing is that the sensor is to provide an always increasing value we should make sure that is the case and that is what the second commit is solving.

**Comment by argoyle** [comment]
Hmmm, average-calculation is not working as I expected. Will fix.

**Comment by argoyle** [comment]
There we go. Stupid operator precedence error introduced by myself. 🤦🏻‍♂️

**Comment by argoyle** [comment]
@jonasbkarlsson I think your problem might have come from the average-handling if there was a garbage message from the Energy Hub so we might not need the special-handling but I can't see that it will cause any problems anyway. I've been running this for some time now in a dev-environment with no issues at least.

**Comment by argoyle** [comment]
Will merge and release this now. It shouldn't make anything worse at least.

**Pull request merged**
