### PR TITLE
fix: don't store events if sensor is not present

### LINKED ISSUE #316: Possible memory leak
I have installed Debian 11 server latest version, installed HA Core (latest) , HACS, MQTT and ha-ferroamp.
As soon as I enable ha-ferroamp and starts to receive data the server memory slowly decreases until HA crashes., rate is about 1 kb per minute.
To test this I have another instance of HA running with a lot of sensors, this server has been running flawless for about a year.
I installed and enabled ha-ferroamp on this server, as soon as I did this the memory slowly decreases.
There are two components involved, MQTT and ha-ferroamp. I am not sure where the memory is allocated and not released, it could be MQTT or it could be ha-ferroamp.
There are no errors in the logs (I have not enabled debug logs yet).
Versions used:
Home Assistant 2023.3.6 
Frontend 20230309.1 - latest 

HACS:
Integration version: | 1.31.0
Frontend version: | 20220906112053
Downloaded repositories: | 4

Debian GNU/Linux 11 (bullseye)

Python 3.10.10.

EnergyHub Extapi Version = 1.2.1

My python skills are limited, I am a PHP-coder,  I have not read up how variables are allocated in python or their sizes. 
It could be that my EnergyHub is manufactured in 2023 and has the latest firmware in it, Ferroamp could have changes something so that data is somewhat different than before.

I will enable debug logging for HA to see if I can get anything useful out of it.
I have the data from the memory sensor if needed.

### PR DESCRIPTION
**Pull request by argoyle**
Might fix #316. Could you try this change locally @mickecamino?

### CODE REVIEW

**Review by henricm — APPROVED** [review]

**Comment by argoyle** [comment]
My instance is stable at 4.9Gb for a couple of hours now.

**Comment by argoyle** [comment]
My instance stayed at 4.9Gb over night as well. Merged and will be release along with another fix.

**Comment by danielolsson100** [comment]
@argoyle ping me if you want me to give it a test in my lab and prod

**Comment by argoyle** [comment]
I think we're fine. Seems to work as expected.

**Pull request merged**
