### PR TITLE
feat: remove model-info from SSO-name

### LINKED ISSUE #26: SSO naming standard alignment between models
Hi
The Gen2 SSO have to long names with model info AND Serial number and that should perhaps be removed.
image
Example: 
SSO-Gen1: FA SSO 19110137 PV String Power
SSO-Gen2: FA SSO PS00990-A04-S21030569 PV String Power
please remove the Part number: "PS00990-A04-S" (and use the last 8 chars in string) in sensor name for SSO sensor types for a more aligned standard between different SSO types.

### PR DESCRIPTION
**Pull request by argoyle**
Closes #26

@danielolsson100 I have removed the model from the name (this is then a breaking change for anyone with Gen2 SSO's since the entity id's will be different) and added it as model to the device instead.

### CODE REVIEW

**Comment by danielolsson100** [comment]
It looks great. I just added the modified file to my production environment now.
image

**Comment by argoyle** [comment]
Nice! Just remembered that there is a way to update the unique id of entities so will add another commit that does that. Then history will stay at least even if Lovelace UI's need to be updated.

**Comment by henricm** [comment]
I'm not sure I understand the`**kwargs` and the purpose of it - maybe you could clarify? 🙂

**Review by henricm — COMMENTED** [review]
I'm not sure I understand the**kwargs and the purpose of it - maybe you could clarify? 🙂

**Comment by argoyle** [comment]
@henricm kwargs is like a hashmap (key/value-pairs). Since the model is not passed from all entities (since we only get this from the SSOs, and only Gen2 at that, right now) I could have passed None for the other ones but I tend to like smaller function signatures and just adding more and more parameters gave me a bad feeling. Now we can add other optional parameters as kwargs and just use them where applicable.

**Comment by henricm** [comment]
Got it - makes sense! thanks for the explanation.

**Comment by argoyle** [comment]
Added the migration. This will actually make upgrade seemless since the old entities will be updated and the old entity id's will be kept. Please have a look @henricm @danielolsson100

**Comment by danielolsson100** [comment]
just tested, seems to be some issues that is logged in home-assistant.log
image

**Comment by argoyle** [comment]
That log statement doesn't have anything to do with the changes in this PR at least. 😊

**Comment by argoyle** [comment]
Baah. Forget me. Thought it was the line we discussed elsewhere. This is definitely related to this change. Are you sure you're running the latest version. I got this in the tests as well and solved it.

**Comment by argoyle** [comment]
It could be that you have entities with the old IDs that the integration wants to convert now. Check your entities list for unavailable sensors. If you don't care for the history you can remove them. If you want the history you have to revert to the master-branch, remove the new sensors and then change to the new version again.

**Comment by argoyle** [comment]
Did you make another try @danielolsson100 after my comment?

**Comment by danielolsson100** [comment]
I cleaned up my old sensors in lab environment and gave it a try 
It now seems to work without errors in the home-assistant.log
I'll now wait for this change to be merged into master before I test it in my production environment

**Pull request merged**
