### PR TITLE
Feature/update 2 python 3 12

### PR DESCRIPTION
**Pull request by nfredrik**
Added some fixes to make the tests go green

### CODE REVIEW

**Comment by argoyle** [comment]
Yeay! Thanks! I started on this path a couple of days back but didn't pull through. If you fix the commitlint-error (probably just a space after the : in the commit-message) and the pre-commit isort error I'm fine with merging.

**Comment by nfredrik** [comment]
> Yeay! Thanks! I started on this path a couple of days back but didn't pull through. If you fix the commitlint-error (probably just a space after the : in the commit-message) and the pre-commit isort error I'm fine with merging.

Fixed!

**Comment by argoyle** [comment]
You have to rewrite the history and change all commit-messages to have the form `chore: <msg>` with the space after the : otherwise commitlint will complain.

**Comment by nfredrik** [comment]
> You have to rewrite the history and change all commit-messages to have the form `chore: <msg>` with the space after the : otherwise commitlint will complain.

Now perhaps?

**Comment by argoyle** [comment]
Still not rewritten, just more commits. I'll fix.

**Comment by argoyle** [comment]
Closed in favor of #530 which was just merged

**Pull request closed without merging**
