### PR TITLE
feat: add sensor for extapi version

### PR DESCRIPTION
**Pull request by argoyle**

### CODE REVIEW

**Comment by danielolsson100** [comment]
tested this version today
I get this message below in the home-assistant.log after rebooting HA host
image

**Comment by argoyle** [comment]
Aaah, removeprefix was a python 3.9+ function. Switched to another way now.

**Comment by danielolsson100** [comment]
The error on the log is gone but this version broke my Gen2 sso sensor below.
image
and there is no API version registered on the sensor
image
image

**Comment by argoyle** [comment]
The SSO-issue was expected since that PR has not been merged yet 😉 
Not sure about the version-sensor though. The last command sent was the extapiversion according to your screenshot. What is the last message on that sensor (if you check the attributes)?

**Comment by argoyle** [comment]
Ping @danielolsson100

**Comment by danielolsson100** [comment]
I tested this in my lab today again instead of my prod environment. 
It seems to be working there without errors in the home-assistant.log

I'll replace my prod code when this change is merged into master

**Pull request merged**
