### PR TITLE
feat: updating readme.md

### PR DESCRIPTION
**Pull request by robinostlund**
Before merging this i need some help from @argoyle:

1. Create a fork of https://github.com/hacs/default
2. Add "henricm/ha-ferroamp", to integration file.
3. Create a new PR to https://github.com/hacs/default with the content:

Topic: Adds new integration [henricm/ha-ferroamp]
Description:
Link to successful HACS action: https://github.com/henricm/ha-ferroamp/actions/runs/2816940946
Link to successful hassfest action (if integration): https://github.com/henricm/ha-ferroamp/actions/runs/2816940959

Then we should be good to go once that pr is merged :)

### CODE REVIEW

**Comment by argoyle** [comment]
Hmmm, HACS-check still fails on issue tracker: https://github.com/hacs/default/pull/1463

**Comment by robinostlund** [comment]
Hmm maby it is checking the latest release if it contains: issue_tracker

**Comment by argoyle** [comment]
Yes, trying that

**Comment by argoyle** [comment]
Seemed to do the trick. 🎉

**Review by argoyle — APPROVED** [review]

**Comment by argoyle** [comment]
Success! Just waiting for approvals and merging then.

**Comment by robinostlund** [comment]
@argoyle sorry saw this in the request template: DO NOT REQUEST REVIEWS, THAT IS JUST RUDE, IF YOU DO THE PULL REQUEST WILL BE CLOSED! and when i asked he closed the pr. Think you need to redo it. Sorry.

**Comment by argoyle** [comment]
New PR: https://github.com/hacs/default/pull/1464

**Comment by argoyle** [comment]
Yeay! HACS default PR is merged. Are we good to go on this one then @robinostlund ?

**Comment by robinostlund** [comment]
Wohoo, gogogo 😊

**Pull request merged**
