### PR TITLE
feat: migrate to new entity naming style

### PR DESCRIPTION
**Pull request by argoyle**
A first stab at supporting the new entity naming style which will be available from next major release 2022.8.x. No merging until that is available at least I would say.

### CODE REVIEW

**Comment by argoyle** [comment]
@henricm Since 2022.8 is released now we could merge this if it looks ok to you.

**Comment by henricm** [comment]
Looks good! This should not change device ids for current installations right?

**Comment by argoyle** [comment]
Nope, just the display names. We do increase min-version of Home Assistant that we support though so I'm a bit hesitant. On the other hand the old version works quite nicely so maybe not a big problem.

**Comment by henricm** [comment]
Sounds great. Agree it's ok to bump mom versions. Users on previous HA versions can use current version.

**Comment by argoyle** [comment]
Merged and released as 1.8.0

**Pull request merged**
