### PR TITLE
feat: add sensor for last command and status

### PR DESCRIPTION
**Pull request by argoyle**

### CODE REVIEW

**Comment by argoyle** [comment]
@danielolsson100 Please take a look at this one as well when you have time? At least a starting-point that can be expanded in the future.

**Comment by danielolsson100** [comment]
I added this version to my lab and noted that the precision of the sensors is hard to understand without definition text :)
image
But I really like the idea to handle this precision issue during config. Nice work on it !
The input values is not applied to all sensors.
Example: I changed the value for A but not all A sensors seems to get the new definition of the precision.
I noted that I am missing (Hz definition)
CONF_PRECISION_FREQUENCY (that value needs all decimals that the FA system can give if the value is to be used)

I'll look into your idea regarding the MQTT response values soon. 
I see what you are trying to achieve in the code but I need to think upon it a bit more and perhaps debug it to see the output and how to handle the syn/ack response in a way that makes sense to HA.

**Comment by argoyle** [comment]
I think you have to refresh the site for the texts to show. Since the PR for adding the options is merged already, please add new issues for the sensors which don't respect the configuration.

**Comment by argoyle** [comment]
In short, the way it works is that it updates the sensor when a new command is sent. When a response or result is received, I check that it's for the last received command before updating the sensor.

**Pull request merged**
