### PR TITLE
feat: add this integration to hacs default

### PR DESCRIPTION
**Pull request by robinostlund**
Added some requirements for being able to add this integration to hacs default.

### CODE REVIEW

**Review by argoyle — APPROVED** [review]
This looks nice. I thought of this when I made the integration HACS-compatible but at the time the requirements seemed to be stricter.

**Comment by robinostlund** [comment]
Crap got error here: https://github.com/hacs/default/pull/1461

```
Run python3 -m scripts.check.owner
Error: 'robinostlund' is not a contributor to 'henricm/ha-ferroamp'
Information: https://hacs.xyz/docs/publish/include#check-owner
Error: Process completed with exit code 1.
```

When this is merged @argoyle can you do a PR to hacs default as you are a contributor? :)

**Comment by argoyle** [comment]
Sure thing. @henricm needs to add the topics to the repository though since I'm not admin/owner (might be that @henricm needs to make the PR to HACS as well depending on what they consider to be contributors). Would something like this be good values for topics perhaps?
```
homeassistant
home-assistant
homeassistant-custom-component
ferroamp
```

**Comment by robinostlund** [comment]
@henricm also add:
```
hacs-default
hacs-integration
```

as topics :)

**Comment by henricm** [comment]
Sounds awesome! I've added the topics now.

**Comment by robinostlund** [comment]
Awesome, can you merge this one then so i can continue with the PR in hacs repo? :) the hacs action needs to be in master for it to be successful.

**Comment by argoyle** [comment]
Done!

**Comment by argoyle** [comment]
Thanks for the contribution. ❤️

**Comment by robinostlund** [comment]
@argoyle are you able to make a PR to hacs default repo? i am not allowed :)

Repo: https://github.com/hacs/default

Add "henricm/ha-ferroamp", to integration file.

Topic: Adds new integration [henricm/ha-ferroamp]
Description:
Link to successful HACS action: https://github.com/henricm/ha-ferroamp/actions/runs/2816940946
Link to successful hassfest action (if integration): https://github.com/henricm/ha-ferroamp/actions/runs/2816940959

Then we should be good to go :)

**Comment by argoyle** [comment]
👍🏻 Will fix tomorrow.

**Pull request merged**
